export const responses = [
  "No",
  "Yes",
  "It was 5 minutes ago",
  "Maybe",
  "On my computer",
  "Have you tried turning it off and on again?",
  "It depends on what you mean by 'working'",
  "Ask me again in 10 minutes",
  "Probably not",
  "Only on Fridays",
  "It's complicated",
  "Define 'working'",
  "Better than yesterday",
  "Not since the last deployment",
  "Ask ChatGPT, not me!",
  "Not according to one guy from Mongolia",
  "01101110 01101111",

  "In theory, yes.",
  "Only in production.",
  "Yes, but the tests are failing.",
  "No, but the tests pass.",
  "Error - unexpected behavior detected.",
  "404 - Function not found.",
  "It depends on your timezone.",
  "Only when the debugger is attached.",
  "It compiles - but that doesn't guarantee it works.",
  "It doesn't compile",
  "After a coffee.",
  "Try clearing your cache - that may make it work.",
  "It requires admin privileges to work.",
  "Only when run with root privileges.",
  "If you believe in miracles.",
  "Yes, but the documentation is garbage.",
  "Say 'please' and try again - politeness might help.",
  "Ask the intern - they might know if it's working.",
  "Ask the deployment pipeline - it will tell you the status.",
  "I saw it working once - intermittently.",
  "Yes - it's a feature, not a bug.",
  "The ghosts in the machine say yes.",
  "The ghosts in the machine say no.",
  "Hardware says no",
  "Software says maybe.",
  "The Project Manager wants you to use Rust instead.",
  "Status: TBD (to be determined).",
  "Even rebooting doesn't help.",
  "I don't know, consult the log files.",
  "It works - but nobody knows why.",
  "Not for everyone.",
  "Ask again at midnight - maybe then it'll work.",
];

export const loadingTexts = [
  "Consulting the code gods",
  "Checking for bugs",
  "Running diagnostics",
  "Asking Stack Overflow",
  "Compiling excuses",
  "Blaming the intern",
  "Unplugging the server",
  "Clearing the cache",
  "Updating dependencies",
  "Praying to the demo gods",
  "Checking if it works on my machine",
  "Running it in production",
  "Turning it off and on again",
  "Consulting the rubber duck",
  "Asking ChatGPT",
  "Touching some grass",
  "Looking at your code",
];
